import { createAsyncThunk, createSlice, PayloadAction } from '@reduxjs/toolkit'

import type { AppState, AppThunk } from '../../app/store'
import { getEventActions } from './eventActionsAPI'

import { EventAction } from '../../app/interfaces'


// interface EventAction {
//     id: number
//     action_id: number
//     event_id: number
//     user_id: number
//     username: string
//     action: {
//         name: string
//         image: string
//     }
//     is_completed: boolean
//     number_participants: number
//     participation_threshold: number
//     points: number
//     inserted_at: Date
//     expired_at: Date
//     updated_at: Date
// }

export interface EventActionsState {
    // eventActions: { id: number, name: string, lauched_by?: string, number_participants?: number, is_completed?: boolean, created_at: Date }[]
    eventActions: EventAction[]
    status: 'idle' | 'loading' | 'failed'
}

const initialState: EventActionsState = {
    eventActions: [],
    status: 'idle',
}

// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.
export const fetchEventActions = createAsyncThunk(
    'eventActions/fetchEventActions',
    async (id: number) => {
        const response = await getEventActions({id})
        // The value we return becomes the `fulfilled` action payload
        console.log('[REDUX] fetchEventActions response: ', response)
        return response
    }
)

export const eventActionsSlice = createSlice({
    name: 'eventActions',
    initialState,
    // The `reducers` field lets us define reducers and generate associated actions
    reducers: {
        // setActions: (state, action: PayloadAction<ActionsState>) => {
        //     console.log('[REDUX authSlice] setActions: ', action)
        //     // state.actions = action.payload.data
        // }
        setEventActions: (state, action: PayloadAction<EventAction[]>) => {
        // setEventActions: (state, action: any[]) => {
            console.log('[REDUX eventActionsSlice] setEventActions action: ', action)
            state.eventActions = action.payload
        },
        addEventAction: (state, action: PayloadAction<EventAction>) => {
            console.log('[REDUX eventActionsSlice] addEventAction action: ', action)
            state.eventActions.push(action.payload)
        }
    },
    // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other slices.
    extraReducers: (builder) => {
        builder
            .addCase(fetchEventActions.pending, (state) => {
                state.status = 'loading'
            })
            .addCase(fetchEventActions.fulfilled, (state, action) => {
                console.log('[REDUX] @Reducer action: ', action)
                state.status = 'idle'
                state.eventActions = action.payload
            })
    },
})

// export const { fetchActions } = actionsSlice.actions
export const { setEventActions, addEventAction } = eventActionsSlice.actions


export const selectEventActions = (state: AppState) => state.eventActions.eventActions
// export const selectEventActions = (state: AppState) => state.eventActions.eventActions


// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
// export const selectCount = (state: AppState) => state.counter.value

export default eventActionsSlice.reducer