import { createAsyncThunk, createSlice, PayloadAction } from '@reduxjs/toolkit'

import type { AppState, AppThunk } from '../../app/store'
import { getEvents } from './eventsAPI'

import { EventUserAction } from '../../app/interfaces'


export interface EventsState {
    // eventActions: { id: number, name: string, lauched_by?: string, number_participants?: number, is_completed?: boolean, created_at: Date }[]
    events: Event[]
    status: 'idle' | 'loading' | 'failed'
}

type DatesInterval = {
    date1: number
    date2: number
}

const initialState: EventsState = {
    events: [],
    status: 'idle',
}

// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.
export const fetchEvents = createAsyncThunk(
    'events/fetchEvents',
    async (dates: DatesInterval) => {
        console.log('[REDUX] fetchEvents dates: ', dates, 'dates: ', dates)
        const response = await getEvents(dates.date1, dates.date2)
        // The value we return becomes the `fulfilled` action payload
        console.log('[REDUX] fetchEvents response: ', response)
        return response
    }
)

export const eventsSlice = createSlice({
    name: 'events',
    initialState,
    // The `reducers` field lets us define reducers and generate associated actions
    reducers: {
        // setActions: (state, action: PayloadAction<ActionsState>) => {
        //     console.log('[REDUX authSlice] setActions: ', action)
        //     // state.actions = action.payload.data
        // }
        setEvents: (state, action: PayloadAction<Event[]>) => {
        // setEventActions: (state, action: any[]) => {
            console.log('[REDUX eventsSlice] setEvents action: ', action)
            state.events = action.payload
        },
        addEvent: (state, action: PayloadAction<Event>) => {
        // addEventUserAction: (state, action: PayloadAction<any>) => {
            console.log('[REDUX eventsSlice] addEvent action: ', action)
            state.events.push(action.payload)
        }
    },
    // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other slices.
    extraReducers: (builder) => {
        builder
            .addCase(fetchEvents.pending, (state) => {
                state.status = 'loading'
            })
            .addCase(fetchEvents.fulfilled, (state, action) => {
                console.log('[REDUX] @Reducer action: ', action)
                state.status = 'idle'
                state.events = action.payload
            })
    },
})

// export const { fetchActions } = actionsSlice.actions
export const { setEvents, addEvent } = eventsSlice.actions


export const selectEvents = (state: AppState) => state.events.events
// export const selectEventActions = (state: AppState) => state.eventActions.eventActions


// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
// export const selectCount = (state: AppState) => state.counter.value

export default eventsSlice.reducer